[package]
name = "smartcalc-app"
version = "1.0.5"
authors = ["Erhan BARIS <erhanbaris@gmail.com>"]
edition = "2018"

[build]
target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
smartcalc = { path = "../smartcalculator/smartcalc/" }
wasm-bindgen = { version = "0.2.79", default-features = false}
console_error_panic_hook = "0.1.6"
js-sys = "0.3.47"
wee_alloc = "0.4.5"
wasm-bindgen-test = "0.3.29"

[dependencies.web-sys]
version = "0.3.4"
features = ['console']

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
